[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run build"

[deploy]
startCommand = "node dist/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
