"use client";

import { useEffect, useRef, useState } from "react";
import { API_URL, apiFetch } from "../../lib/api";
import { getStoredToken } from "../../lib/auth-storage";

interface BrandingConfig {
  logoUrl: string | null;
  brandColor: string;
  agencyName: string;
}

const PRESET_COLORS = ["#06b6d4", "#8b5cf6", "#10b981", "#f59e0b", "#ef4444", "#3b82f6", "#ec4899", "#ffffff"];

function ReportPreview({ config }: { config: BrandingConfig }) {
  const color = /^#[0-9a-fA-F]{6}$/.test(config.brandColor) ? config.brandColor : "#06b6d4";
  return (
    <div className="overflow-hidden rounded-2xl border border-white/10 bg-[#0b0d1a] text-white" style={{ fontFamily: "sans-serif" }}>
      <div className="flex items-center justify-between px-5 py-4" style={{ borderBottom: `2px solid ${color}20` }}>
        <div className="flex items-center gap-3">
          {config.logoUrl ? (
            <img src={config.logoUrl} alt="logo" className="h-7 w-auto object-contain" onError={(e) => ((e.currentTarget.style.display = "none"))} />
          ) : (
            <div className="flex h-7 items-center rounded px-3 text-xs font-bold" style={{ background: `${color}20`, color }}>
              {config.agencyName || "Your Agency"}
            </div>
          )}
        </div>
        <div className="text-right">
          <p className="text-[10px] text-white/40">Client Name</p>
          <p className="text-[9px] text-white/25">Apr 2025 · Generated by {config.agencyName || "Your Agency"}</p>
        </div>
      </div>
      <div className="grid grid-cols-4 gap-2 px-5 py-3">
        {["Followers", "Engagement", "Reach", "Impressions"].map((label, i) => (
          <div key={i} className="rounded-lg bg-white/5 p-2 text-center">
            <p className="text-[9px] uppercase tracking-wide text-white/30">{label}</p>
            <p className="mt-0.5 text-xs font-bold text-white">-</p>
          </div>
        ))}
      </div>
      <div className="px-5 pb-4">
        <div className="flex items-center gap-3 rounded-xl bg-white/5 p-3">
          <div className="text-2xl font-black" style={{ color }}>
            78
          </div>
          <div className="flex-1 space-y-1">
            {["Engagement", "Growth", "Consistency", "Reach"].map((l, i) => (
              <div key={i} className="flex items-center gap-2">
                <span className="w-16 shrink-0 text-[9px] text-white/30">{l}</span>
                <div className="h-1 flex-1 rounded-full bg-white/10">
                  <div className="h-full rounded-full" style={{ width: `${[75, 60, 85, 55][i]}%`, background: color }} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
      <div className="flex justify-between border-t border-white/8 px-5 py-2.5 text-[9px] text-white/20">
        <span>Prepared by {config.agencyName || "Your Agency"}</span>
        <span>Confidential</span>
      </div>
    </div>
  );
}

export function BrandingSettings() {
  const [config, setConfig] = useState<BrandingConfig>({ logoUrl: null, brandColor: "#06b6d4", agencyName: "" });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState("");
  const fileRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    apiFetch<BrandingConfig>("/agency/branding")
      .then((d) => {
        setConfig(d);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const patch = (p: Partial<BrandingConfig>) => {
    setConfig((prev) => ({ ...prev, ...p }));
    setSaved(false);
  };

  const handleLogoUpload = async (file: File) => {
    if (!file.type.startsWith("image/")) {
      setError("Please upload an image file (PNG, JPG, SVG)");
      return;
    }
    if (file.size > 2 * 1024 * 1024) {
      setError("Logo must be under 2MB");
      return;
    }
    setUploading(true);
    setError("");
    try {
      const token = getStoredToken();
      const form = new FormData();
      form.append("file", file);
      const res = await fetch(`${API_URL}/agency/branding/logo`, {
        method: "POST",
        headers: token ? { Authorization: `Bearer ${token}` } : {},
        body: form,
        credentials: "include"
      });
      if (!res.ok) throw new Error("Upload failed");
      const d = (await res.json()) as { url?: string };
      patch({ logoUrl: d.url ?? null });
    } catch {
      setError("Logo upload failed. Try again.");
    } finally {
      setUploading(false);
    }
  };

  const save = async () => {
    setSaving(true);
    setError("");
    try {
      await apiFetch("/agency/branding", {
        method: "POST",
        body: JSON.stringify({
          brandColor: config.brandColor,
          agencyName: config.agencyName,
          logoUrl: config.logoUrl
        })
      });
      setSaved(true);
    } catch {
      setError("Could not save branding. Try again.");
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="space-y-4">
        {[1, 2, 3].map((i) => (
          <div key={i} className="h-16 animate-pulse rounded-2xl bg-white/5" />
        ))}
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 gap-8 lg:grid-cols-2">
      <div className="space-y-6">
        <div className="space-y-2">
          <label className="text-xs uppercase tracking-widest text-white/40">Agency name</label>
          <input
            type="text"
            value={config.agencyName}
            onChange={(e) => patch({ agencyName: e.target.value })}
            placeholder="Your Agency Name"
            className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm text-white outline-none transition-colors placeholder:text-white/25 focus:border-cyan-400/50"
          />
        </div>

        <div className="space-y-2">
          <label className="text-xs uppercase tracking-widest text-white/40">Agency logo</label>
          <div
            onClick={() => fileRef.current?.click()}
            onDragOver={(e) => e.preventDefault()}
            onDrop={(e) => {
              e.preventDefault();
              const file = e.dataTransfer.files[0];
              if (file) void handleLogoUpload(file);
            }}
            className="relative cursor-pointer rounded-2xl border-2 border-dashed border-white/15 p-6 text-center transition-all hover:border-cyan-400/40 hover:bg-white/[0.03]"
          >
            {config.logoUrl ? (
              <div className="space-y-3">
                <img src={config.logoUrl} alt="logo" className="mx-auto h-12 object-contain" onError={() => patch({ logoUrl: null })} />
                <p className="text-xs text-white/35">Click or drag to replace</p>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    patch({ logoUrl: null });
                  }}
                  className="text-xs text-red-400/70 transition-colors hover:text-red-400"
                >
                  Remove logo
                </button>
              </div>
            ) : (
              <div className="space-y-2">
                <div className="text-3xl">🖼️</div>
                <p className="text-sm text-white/50">{uploading ? "Uploading..." : "Click or drag your logo here"}</p>
                <p className="text-xs text-white/25">PNG, JPG, or SVG · Max 2MB</p>
              </div>
            )}
            {uploading && (
              <div className="absolute inset-0 flex items-center justify-center rounded-2xl bg-black/50">
                <div className="h-6 w-6 animate-spin rounded-full border-2 border-white/20 border-t-cyan-400" />
              </div>
            )}
          </div>
          <input
            ref={fileRef}
            type="file"
            accept="image/*"
            className="hidden"
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) void handleLogoUpload(file);
            }}
          />
        </div>

        <div className="space-y-3">
          <label className="text-xs uppercase tracking-widest text-white/40">Brand colour</label>
          <div className="flex flex-wrap gap-2">
            {PRESET_COLORS.map((c) => (
              <button
                key={c}
                onClick={() => patch({ brandColor: c })}
                className="h-8 w-8 rounded-full border-2 transition-all"
                style={{
                  background: c,
                  borderColor: config.brandColor === c ? "white" : "transparent",
                  transform: config.brandColor === c ? "scale(1.15)" : "scale(1)"
                }}
              />
            ))}
          </div>
          <div className="flex items-center gap-3">
            <input type="color" value={config.brandColor} onChange={(e) => patch({ brandColor: e.target.value })} className="h-10 w-10 cursor-pointer rounded-xl border-0 bg-transparent" />
            <input
              type="text"
              value={config.brandColor}
              onChange={(e) => patch({ brandColor: e.target.value })}
              placeholder="#06b6d4"
              className="flex-1 rounded-xl border border-white/10 bg-white/5 px-3 py-2 font-mono text-sm text-white outline-none transition-colors focus:border-cyan-400/50"
            />
          </div>
        </div>

        {error ? <p className="text-xs text-red-400">{error}</p> : null}

        <button
          onClick={() => void save()}
          disabled={saving}
          className={`w-full rounded-xl py-3 text-sm font-bold transition-all disabled:opacity-40 ${
            saved ? "border border-emerald-400/30 bg-emerald-400/15 text-emerald-400" : "bg-cyan-500 text-black hover:bg-cyan-400"
          }`}
        >
          {saving ? "Saving..." : saved ? "✓ Branding saved" : "Save branding"}
        </button>
      </div>

      <div className="space-y-3">
        <p className="text-xs uppercase tracking-widest text-white/40">Live report preview</p>
        <ReportPreview config={config} />
        <p className="text-center text-xs text-white/25">This is how your exported PDF reports will look</p>
      </div>
    </div>
  );
}
