export type ReportBranding = {
  agencyName?: string | null;
  brandColor?: string | null;
  logoUrl?: string | null;
};

export type BaseTemplateInput = {
  title: string;
  subtitle?: string;
  generatedAt?: Date;
  branding: ReportBranding;
  applyWatermark?: boolean;
  contentHtml: string;
};

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function brandColor(color?: string | null): string {
  if (typeof color === "string" && /^#[0-9a-fA-F]{6}$/.test(color.trim())) {
    return color.trim();
  }
  return "#6366F1";
}

function logoMarkup(input: ReportBranding): string {
  if (input.logoUrl) {
    return `<img src="${escapeHtml(input.logoUrl)}" alt="Agency logo" class="agency-logo" />`;
  }
  return `<div class="agency-chip">${escapeHtml(input.agencyName ?? "Pulse")}</div>`;
}

export function reportFooterTemplate(branding: ReportBranding): string {
  void branding;
  return `
  <div style="font-family:Inter,system-ui,sans-serif;font-size:11px;color:#94a3b8;width:100%;padding:0 10mm;display:flex;justify-content:space-between;border-top:1px solid #e2e8f0;padding-top:6px;">
    <span>Generated by Pulse</span>
    <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
  </div>`;
}

export function renderBaseTemplate(input: BaseTemplateInput): string {
  const agency = escapeHtml(input.branding.agencyName ?? "Pulse");
  const accent = brandColor(input.branding.brandColor);
  const generated = (input.generatedAt ?? new Date()).toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Asia/Kolkata"
  });

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(input.title)}</title>
    <style>
      :root { --brand: ${accent}; --ink:#0f172a; --secondary:#475569; --muted:#94a3b8; --line:#e2e8f0; --surface:#ffffff; --bg:#f8fafc; }
      * { box-sizing: border-box; }
      body { margin:0; font-family: Inter, system-ui, sans-serif; color:var(--ink); background:var(--bg); font-size:13px; }
      .page { width: 100%; min-height: 100vh; padding: 40px; }
      .container { max-width: 720px; margin: 0 auto; }
      .header { display:flex; justify-content:space-between; align-items:flex-start; gap:16px; border-bottom:1px solid var(--line); padding-bottom:16px; }
      .header-left { display:flex; gap:12px; align-items:flex-start; }
      .agency-logo { width:auto; height:32px; object-fit:contain; border-radius:6px; }
      .agency-chip { background:#eef2ff; color:var(--brand); border:1px solid #dbeafe; border-radius:8px; padding:7px 10px; font-size:11px; font-weight:600; }
      .agency-name { font-size:16px; font-weight:600; line-height:1.3; color:var(--ink); margin:0 0 8px; }
      .title { font-size:22px; line-height:1.3; font-weight:700; margin:0; color:var(--ink); }
      .page-title { font-size:28px; line-height:1.2; font-weight:700; margin:32px 0 8px; color:var(--ink); }
      .subtitle { font-size:13px; color:var(--secondary); margin:0; }
      .meta { font-size:11px; color:var(--muted); margin-top:2px; }
      .content { margin-top: 32px; }
      .section { margin-bottom: 32px; }
      .section-title { margin:0 0 16px; font-size:18px; line-height:1.3; font-weight:600; color:var(--ink); display:flex; align-items:center; gap:8px; }
      .section-accent { width:3px; height:18px; border-radius:99px; background:var(--brand); }
      .grid-2 { display:grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap:16px; }
      .card { background:var(--surface); border:1px solid var(--line); border-radius:12px; padding:16px; box-shadow:0 1px 2px rgba(15,23,42,.04); }
      .caption { font-size:11px; color:var(--muted); }
      .muted { color:var(--secondary); }
      .divider { border:0; border-top:1px solid var(--line); margin:16px 0; }
        .section, .card { break-inside: avoid; page-break-inside: avoid; }
        .watermark {
          position: fixed;
          bottom: 14px;
          left: 0;
          right: 0;
          text-align: center;
          font-size: 10px;
          color: #94a3b8;
          opacity: 0.55;
          pointer-events: none;
        }
    </style>
  </head>
  <body>
    ${input.applyWatermark ? `<div class="watermark">Generated by Pulse</div>` : ""}
    <main class="page">
      <div class="container">
        <header class="header">
          <div class="header-left">
            ${logoMarkup(input.branding)}
            <div>
              <p class="agency-name">${agency}</p>
              <h1 class="title">${escapeHtml(input.title)}</h1>
              <p class="meta">Generated ${generated}</p>
            </div>
          </div>
        </header>
        <h2 class="page-title">${escapeHtml(input.title)}</h2>
        ${input.subtitle ? `<p class="subtitle">${escapeHtml(input.subtitle)}</p>` : ""}
        <section class="content">${input.contentHtml}</section>
      </div>
    </main>
  </body>
</html>`;
}

